spring:
  application:
    name: lbs_ch05

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe   # 포트/서비스명 맞게 수정하세요
    username: C##user1
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none      # create / update / validate / none
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never	
